version: '3.9'

services:
  # SigNoz Services
  signoz-collector:
    image: signoz/signoz-otel-collector:0.88.11
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./signoz-config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=signoz-otel-collector,service.version=0.88.11
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - signoz-clickhouse
      - signoz-kafka

  signoz-query-service:
    image: signoz/query-service:0.38.0
    command: ["-config=/root/config/prometheus.yml"]
    volumes:
      - ./signoz-config/prometheus.yml:/root/config/prometheus.yml
      - ./signoz-data/signoz/:/var/lib/signoz/
    environment:
      - ClickHouseUrl=tcp://signoz-clickhouse:9000
      - STORAGE=clickhouse
      - GODEBUG=netdns=go
      - TELEMETRY_ENABLED=true
      - DEPLOYMENT_TYPE=docker-standalone-amd
    ports:
      - "8080:8080"
    depends_on:
      - signoz-clickhouse
      - signoz-kafka

  signoz-frontend:
    image: signoz/frontend:0.38.0
    ports:
      - "3301:3301"
    depends_on:
      - signoz-query-service
    volumes:
      - ./signoz-config/nginx.conf:/etc/nginx/conf.d/default.conf

  signoz-alertmanager:
    image: signoz/alertmanager:0.23.0-0.1
    volumes:
      - ./signoz-data/alertmanager:/data
    depends_on:
      - signoz-query-service
    command:
      - --queryService.url=http://signoz-query-service:8080
      - --storage.path=/data

  signoz-clickhouse:
    image: clickhouse/clickhouse-server:23.7.3-alpine
    tty: true
    depends_on:
      - signoz-zookeeper
    logging:
      options:
        max-size: 50m
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    container_name: signoz-clickhouse
    hostname: clickhouse
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - ./signoz-config/clickhouse-config.xml:/etc/clickhouse-server/config.xml
      - ./signoz-config/clickhouse-users.xml:/etc/clickhouse-server/users.xml
      - ./signoz-data/clickhouse/:/var/lib/clickhouse/

  signoz-kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: signoz-kafka
    depends_on:
      - signoz-zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'signoz-zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

  signoz-zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: signoz-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # MySQL with monitoring
  mysql-monitored:
    image: mysql:8.0
    container_name: automated-mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: Secret5555
      MYSQL_DATABASE: project_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-config/my.cnf:/etc/mysql/conf.d/my.cnf
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: --general-log=1 --general-log-file=/var/lib/mysql/general.log --slow-query-log=1 --slow-query-log-file=/var/lib/mysql/slow.log --long_query_time=2

volumes:
  signoz-data:
  mysql-data:
